"""Native LLM context hydration for images generated by Nymeria tools."""

from __future__ import annotations

import base64
import logging
import mimetypes
import os
from pathlib import Path
from typing import Any

from langchain_core.messages import BaseMessage, ToolMessage

from ..config.model_capabilities import supports_vision
from ..vendor.react_agent.config import LLMConfig

logger = logging.getLogger(__name__)

NATIVE_IMAGE_ARTIFACT_KEY = "nymeria_native_image"
_MAX_NATIVE_IMAGE_COUNT = 3
_MAX_NATIVE_IMAGE_BYTES = 8 * 1024 * 1024
_SUPPORTED_IMAGE_MIME_TYPES = {
    "image/png",
    "image/jpeg",
    "image/webp",
    "image/gif",
}


def _workspace_dir() -> Path:
    return Path(os.environ.get("NYMERIA_WORKSPACE_DIR", "/workspace")).resolve()


def _copy_message_with_content(message: BaseMessage, content: Any) -> BaseMessage:
    if hasattr(message, "model_copy"):
        return message.model_copy(update={"content": content})
    return message.copy(update={"content": content})


def _get_native_image_metadata(message: ToolMessage) -> dict[str, Any] | None:
    artifact = getattr(message, "artifact", None)
    if not isinstance(artifact, dict):
        return None

    metadata = artifact.get(NATIVE_IMAGE_ARTIFACT_KEY)
    if not isinstance(metadata, dict):
        return None
    if metadata.get("native_context_enabled") is False:
        return None
    return metadata


def provider_supports_generated_image_context(llm_config: LLMConfig | None) -> bool:
    """Return whether generated images can be replayed as native vision input."""
    if llm_config is None:
        return False

    model = (llm_config.model or "").strip()
    if not model or not supports_vision(model):
        return False

    provider = (llm_config.provider or "").strip().lower()
    if provider == "anthropic":
        return True

    if provider in {"openai", "openrouter"}:
        return (llm_config.openai_api_mode or "responses") == "responses"

    return False


def _resolve_image_file(metadata: dict[str, Any]) -> tuple[Path, str] | None:
    raw_path = metadata.get("path")
    if not isinstance(raw_path, str) or not raw_path.strip():
        return None

    workspace = _workspace_dir()
    try:
        path = Path(raw_path).resolve()
    except Exception:
        return None

    if not path.is_relative_to(workspace):
        logger.warning("[IMAGE CONTEXT] Skipping generated image outside workspace: %s", raw_path)
        return None
    if not path.is_file():
        logger.info("[IMAGE CONTEXT] Generated image no longer exists: %s", path)
        return None

    size = path.stat().st_size
    if size > _MAX_NATIVE_IMAGE_BYTES:
        logger.info(
            "[IMAGE CONTEXT] Skipping generated image over native context limit: %s bytes=%d",
            path,
            size,
        )
        return None

    mime_type = metadata.get("mime_type")
    if not isinstance(mime_type, str) or not mime_type:
        mime_type = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
    if mime_type not in _SUPPORTED_IMAGE_MIME_TYPES:
        logger.info("[IMAGE CONTEXT] Skipping unsupported image MIME type %s for %s", mime_type, path)
        return None

    return path, mime_type


def _image_data_url(path: Path, mime_type: str) -> str:
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def _content_with_image(content: Any, data_url: str) -> list[Any]:
    blocks: list[Any]
    if isinstance(content, list):
        blocks = list(content)
    elif isinstance(content, str):
        blocks = [{"type": "text", "text": content}]
    else:
        blocks = [{"type": "text", "text": str(content)}]

    blocks.append({
        "type": "image_url",
        "image_url": {"url": data_url},
    })
    return blocks


def hydrate_generated_images_for_llm(
    messages: list[BaseMessage],
    llm_config: LLMConfig | None,
) -> list[BaseMessage]:
    """Attach recent generated images to cloned ToolMessages for the next LLM call.

    The checkpoint stores only small artifact metadata. Image bytes are read from
    the workspace and converted to data URLs immediately before provider calls,
    so history stays compact while vision-capable models can inspect the result.
    """
    if not provider_supports_generated_image_context(llm_config):
        return messages

    selected: list[tuple[int, dict[str, Any]]] = []
    for index in range(len(messages) - 1, -1, -1):
        message = messages[index]
        if not isinstance(message, ToolMessage):
            continue
        metadata = _get_native_image_metadata(message)
        if metadata is None:
            continue
        selected.append((index, metadata))
        if len(selected) >= _MAX_NATIVE_IMAGE_COUNT:
            break

    if not selected:
        return messages

    by_index = dict(selected)
    hydrated: list[BaseMessage] = []
    changed = False
    hydrated_count = 0
    for index, message in enumerate(messages):
        metadata = by_index.get(index)
        if metadata is None or not isinstance(message, ToolMessage):
            hydrated.append(message)
            continue

        resolved = _resolve_image_file(metadata)
        if resolved is None:
            hydrated.append(message)
            continue

        path, mime_type = resolved
        try:
            data_url = _image_data_url(path, mime_type)
        except OSError as exc:
            logger.warning("[IMAGE CONTEXT] Failed to read generated image %s: %s", path, exc)
            hydrated.append(message)
            continue

        hydrated.append(_copy_message_with_content(
            message,
            _content_with_image(message.content, data_url),
        ))
        changed = True
        hydrated_count += 1

    if changed:
        logger.info("[IMAGE CONTEXT] Attached %d generated image(s) as native LLM context", hydrated_count)
    return hydrated if changed else messages
