"""Native LLM context hydration for images generated by Nymeria tools."""

from __future__ import annotations

import base64
import logging
import mimetypes
import os
from pathlib import Path
from typing import Any

from langchain_core.messages import BaseMessage, ToolMessage

from ..config.model_capabilities import get_attachment_limits, supports_vision
from ..vendor.react_agent.config import LLMConfig

logger = logging.getLogger(__name__)

# Artifact metadata key for an image to replay as native vision input. The
# nested ``source`` field is SECURITY-RELEVANT: ``_resolve_image_file`` exempts
# only ``source == "file_read"`` from workspace confinement. All producers are
# first-party tool returns (build via ``build_native_image_artifact``); never
# derive ``source`` from untrusted/user-controlled input.
NATIVE_IMAGE_ARTIFACT_KEY = "nymeria_native_image"
_MAX_NATIVE_IMAGE_COUNT = 3
_MAX_NATIVE_IMAGE_BYTES = 8 * 1024 * 1024
_SUPPORTED_IMAGE_MIME_TYPES = {
    "image/png",
    "image/jpeg",
    "image/webp",
    "image/gif",
}


def _workspace_dir() -> Path:
    return Path(os.environ.get("NYMERIA_WORKSPACE_DIR", "/workspace")).resolve()


def _copy_message_with_content(message: BaseMessage, content: Any) -> BaseMessage:
    if hasattr(message, "model_copy"):
        return message.model_copy(update={"content": content})
    return message.copy(update={"content": content})


def _get_native_image_metadata(message: ToolMessage) -> dict[str, Any] | None:
    artifact = getattr(message, "artifact", None)
    if not isinstance(artifact, dict):
        return None

    metadata = artifact.get(NATIVE_IMAGE_ARTIFACT_KEY)
    if not isinstance(metadata, dict):
        return None
    if metadata.get("native_context_enabled") is False:
        return None
    return metadata


def build_native_image_artifact(
    path: Path | str,
    mime_type: str,
    *,
    source: str,
    **meta: Any,
) -> dict[str, Any]:
    """Build the ``content_and_artifact`` payload that replays an image to the LLM.

    ``source`` tags where the image came from ("image_gen", "file_read", ...).
    The hydration path keys workspace-confinement off this tag: only
    ``source == "file_read"`` is allowed outside the workspace (file_read already
    reads arbitrary paths), so any other / missing source stays confined.
    """
    payload: dict[str, Any] = {
        "path": str(path),
        "mime_type": mime_type,
        "native_context_enabled": True,
        "source": source,
    }
    payload.update(meta)
    return {NATIVE_IMAGE_ARTIFACT_KEY: payload}


def explain_image_context_support(llm_config: LLMConfig | None) -> tuple[bool, str]:
    """Return ``(supported, reason)`` for replaying an image as native vision input.

    Reasons: ``supported``, ``non_vision_model``, ``chat_completions_route``,
    ``unsupported_provider``, ``unknown``. The single source of truth shared by
    the hydration gate and ``file_read``'s agent-facing warning.
    """
    if llm_config is None:
        return False, "unknown"

    model = (llm_config.model or "").strip()
    if not model or not supports_vision(model):
        return False, "non_vision_model"

    provider = (llm_config.provider or "").strip().lower()
    if provider == "anthropic":
        return True, "supported"

    if provider in {"openai", "openrouter"}:
        if (llm_config.openai_api_mode or "responses") == "responses":
            return True, "supported"
        return False, "chat_completions_route"

    return False, "unsupported_provider"


def provider_supports_generated_image_context(llm_config: LLMConfig | None) -> bool:
    """Return whether generated images can be replayed as native vision input."""
    return explain_image_context_support(llm_config)[0]


def _resolve_image_file(
    metadata: dict[str, Any],
    max_image_bytes: int = _MAX_NATIVE_IMAGE_BYTES,
) -> tuple[Path, str] | None:
    raw_path = metadata.get("path")
    if not isinstance(raw_path, str) or not raw_path.strip():
        return None

    try:
        path = Path(raw_path).resolve()
    except Exception:
        return None

    # file_read surfaces images from arbitrary paths (its existing read scope),
    # so it is exempt from workspace confinement. Generated images (and any
    # untagged artifact) stay confined as a fail-safe.
    if metadata.get("source") != "file_read":
        workspace = _workspace_dir()
        if not path.is_relative_to(workspace):
            logger.warning("[IMAGE CONTEXT] Skipping generated image outside workspace: %s", raw_path)
            return None
    if not path.is_file():
        logger.info("[IMAGE CONTEXT] Image no longer exists: %s", path)
        return None

    size = path.stat().st_size
    if size > max_image_bytes:
        logger.info(
            "[IMAGE CONTEXT] Skipping image over model size limit: %s bytes=%d limit=%d",
            path,
            size,
            max_image_bytes,
        )
        return None

    mime_type = metadata.get("mime_type")
    if not isinstance(mime_type, str) or not mime_type:
        mime_type = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
    if mime_type not in _SUPPORTED_IMAGE_MIME_TYPES:
        logger.info("[IMAGE CONTEXT] Skipping unsupported image MIME type %s for %s", mime_type, path)
        return None

    return path, mime_type


def _image_data_url(path: Path, mime_type: str) -> str:
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def _content_with_image(content: Any, data_url: str) -> list[Any]:
    blocks: list[Any]
    if isinstance(content, list):
        blocks = list(content)
    elif isinstance(content, str):
        blocks = [{"type": "text", "text": content}]
    else:
        blocks = [{"type": "text", "text": str(content)}]

    blocks.append({
        "type": "image_url",
        "image_url": {"url": data_url},
    })
    return blocks


def hydrate_generated_images_for_llm(
    messages: list[BaseMessage],
    llm_config: LLMConfig | None,
) -> list[BaseMessage]:
    """Attach recent generated images to cloned ToolMessages for the next LLM call.

    The checkpoint stores only small artifact metadata. Image bytes are read from
    the workspace and converted to data URLs immediately before provider calls,
    so history stays compact while vision-capable models can inspect the result.
    """
    if not provider_supports_generated_image_context(llm_config):
        return messages

    # Model-specific byte cap (live override -> family fallback -> global
    # default), so a model that accepts larger images is not penalized.
    max_image_bytes = _MAX_NATIVE_IMAGE_BYTES
    if llm_config is not None:
        cap = get_attachment_limits(llm_config.model or "").get("max_image_bytes")
        if isinstance(cap, int) and cap > 0:
            max_image_bytes = cap

    selected: list[tuple[int, dict[str, Any]]] = []
    for index in range(len(messages) - 1, -1, -1):
        message = messages[index]
        if not isinstance(message, ToolMessage):
            continue
        metadata = _get_native_image_metadata(message)
        if metadata is None:
            continue
        selected.append((index, metadata))
        if len(selected) >= _MAX_NATIVE_IMAGE_COUNT:
            break

    if not selected:
        return messages

    by_index = dict(selected)
    hydrated: list[BaseMessage] = []
    changed = False
    hydrated_count = 0
    for index, message in enumerate(messages):
        metadata = by_index.get(index)
        if metadata is None or not isinstance(message, ToolMessage):
            hydrated.append(message)
            continue

        resolved = _resolve_image_file(metadata, max_image_bytes)
        if resolved is None:
            hydrated.append(message)
            continue

        path, mime_type = resolved
        try:
            data_url = _image_data_url(path, mime_type)
        except OSError as exc:
            logger.warning("[IMAGE CONTEXT] Failed to read generated image %s: %s", path, exc)
            hydrated.append(message)
            continue

        hydrated.append(_copy_message_with_content(
            message,
            _content_with_image(message.content, data_url),
        ))
        changed = True
        hydrated_count += 1

    if changed:
        logger.info("[IMAGE CONTEXT] Attached %d generated image(s) as native LLM context", hydrated_count)
    return hydrated if changed else messages
