"""Generated on-disk map of the Nymeria resource stores.

Slice 1 of the resource-filesystem-layout plan (backlog #75): the runtime
data dir is the agent's resource root, and this module writes the live
per-deployment index into it at API startup: ``README.md`` plus JSON Schemas
for the JSON-backed stores under ``schema/``. Writes are write-if-changed so
boots do not churn mtimes; the artifacts are Nymeria-owned, so manual edits
to them are regenerated (every other file under the root is live state and
is never touched here). The durable generic knowledge lives in the bundled
``nymeria-resources`` skill, which points at these artifacts for live paths.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class _StoreRow:
    path: str
    what: str
    scope: str
    hot_load: str
    posture: str


_STORE_ROWS: tuple[_StoreRow, ...] = (
    _StoreRow(
        "custom_tools/<id>.json",
        "Custom tool and workflow definitions (http, mcp, python, workflow types)",
        "global",
        "yes",
        "files-as-truth; python/workflow source is approval-gated (see below)",
    ),
    _StoreRow(
        "custom_tools/revisions/<tool_id>/<hash>.py",
        "Python/workflow source revisions (last 10 kept)",
        "global",
        "n/a",
        "publish via tool_create; raw edits are inert until re-approval",
    ),
    _StoreRow(
        "hooks/<user>.json",
        "Lifecycle hook definitions (schema/hook_store.schema.json)",
        "per user",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "triggers/<user>.json",
        "Event trigger definitions (schema/trigger_store.schema.json)",
        "per user",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "skills/global/<name>/SKILL.md; skills/users/<id>/<name>/SKILL.md",
        "Skills and Skill Kits (kit = skill with required_tools); same-name "
        "user/global skills shadow bundled ones",
        "global + per user",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "mcp_servers/<id>.json",
        "MCP server definitions (schema/mcp_server.schema.json)",
        "global",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "thread_configs/<thread_id>.json",
        "Per-thread config: model, tools, skills, dreaming "
        "(schema/thread_config.schema.json)",
        "per thread",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "dream_prompt.md, dream_kickoff.md",
        "Dream prompt overrides; file absent = built-in default",
        "global",
        "yes",
        "files-as-truth",
    ),
    _StoreRow(
        "system_prompt.md",
        "System prompt override; file absent = built-in default",
        "global",
        "no (read at startup; apply via settings update or restart)",
        "files-as-truth",
    ),
    _StoreRow(
        "workflows/state/",
        "Workflow scratch state (nym.state)",
        "per workflow + user",
        "yes",
        "treat as read-only: workflows do not expect concurrent external edits",
    ),
    _StoreRow(
        "hooks/<user>_executions.json, triggers/<user>_executions.json",
        "Execution logs",
        "per user",
        "n/a",
        "generated, read-only",
    ),
    _StoreRow(
        "README.md, schema/",
        "This map (generated at startup, write-if-changed)",
        "global",
        "n/a",
        "generated, manual edits are overwritten",
    ),
)

_OPERATIONAL_DIRS = (
    "activity/", "auth_tokens/", "backups/", "cli_history/", "flags/",
    "goals/", "hooks/approvals/", "logs/", "mcp_install_previews/",
    "mcp_runtimes/", "notifications/", "thread_metadata/", "thread_notes/",
    "todos/", "tool_drafts/", "users/", "voice/", "workflows/pending/",
    "workflows/runs/",
)


def render_resource_readme() -> str:
    """Render the root README.md content (deterministic, no timestamps)."""
    lines: list[str] = [
        "# Nymeria resource root",
        "",
        "Generated by Nymeria at startup (write-if-changed); manual edits to",
        "this file and to `schema/` are overwritten. Everything else under",
        "this directory is live runtime state: every agent-owned store",
        "(custom tools, workflows, hooks, triggers, skills and kits, MCP",
        "server configs, thread configs, prompt overrides) lives here as",
        "plain files, editable with the generic file tools. The bundled",
        "`nymeria-resources` skill carries the editing rules; this file is",
        "the live per-deployment index it points at.",
        "",
        "## Resource stores",
        "",
        "| Path | What | Scope | Hot-load | Edit posture |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in _STORE_ROWS:
        lines.append(
            f"| `{row.path}` | {row.what} | {row.scope} | {row.hot_load} "
            f"| {row.posture} |"
        )
    lines += [
        "",
        'Hot-load "yes": a direct file edit is picked up on next use (checks',
        "are debounced to about two seconds), no restart needed. Same-instant",
        "rewrites that keep the byte size identical can be missed; when in",
        "doubt, touch the file again or use the matching authoring tool.",
        "",
        "`<store>.json.sig` sidecar files beside the hook and trigger stores",
        "are Nymeria bookkeeping (they let loaders tell tool-driven writes",
        "from raw edits, for the activity log). Leave them alone; deleting",
        "one is harmless beyond a missed or duplicate audit line.",
        "",
        "## Approval-gated content",
        "",
        "Python custom tools and workflow definitions run behind",
        "execution-time approval gates keyed to a content hash. Editing",
        "their source on disk is allowed but makes them inert: every call",
        "re-checks the hash and refuses until an admin re-approves",
        "(tool_create publish, or the workflow approval surfaces).",
        "",
        "## Off limits: credentials",
        "",
        "Anything holding credentials (the encrypted account vault and OAuth",
        "token caches) is not part of this interface. Use auth_write and",
        "auth_test (see the credential-management skill) instead.",
        "",
        "## Operational state (not yours to edit)",
        "",
        "Readable for debugging, but edits can corrupt runtime state:",
        "",
        "  " + ", ".join(f"`{d}`" for d in _OPERATIONAL_DIRS) + ",",
        "  plus the SQLite databases and token files at this root.",
        "",
        "## Etiquette for raw edits",
        "",
        "- Prefer the purpose-built tools (tool_create, hook_config,",
        "  trigger_config, skill_write, mcp_manage, workflow_info) when one",
        "  fits: they validate input and keep connected clients current.",
        "- Do not raw-edit a store that a running turn is also mutating via",
        "  tools: writes are whole-file last-writer-wins.",
        "- A malformed edit to a JSON store file is quarantined on next load:",
        "  the file moves into a `quarantine/` subdirectory beside the store",
        "  (timestamped, bytes preserved) and the store loads without it. Fix",
        "  the quarantined copy and move it back. A corrupt SKILL.md is",
        "  skipped (or served from cache) instead of quarantined.",
        "- Raw edits emit no UI events; open client panels stay stale until",
        "  refreshed.",
        "",
        "## Schemas",
        "",
        "`schema/*.schema.json` (generated) describe the JSON store file",
        "formats. Skills are markdown with YAML frontmatter; see the",
        "skill-management skill.",
        "",
    ]
    return "\n".join(lines)


def _render_schemas() -> Iterable[tuple[str, str]]:
    """Yield (filename, content) pairs for the JSON-backed store schemas.

    Imports are function-local: the store modules pull in heavier deps and
    some import back into core. Guarded so an import failure skips the
    schemas instead of aborting the whole map write (the caller's except
    clause only covers OSError, and the README should land regardless).
    """
    try:
        from .hook_manager import HookStore
        from .trigger_manager import TriggerStore
        from .thread_config import ThreadConfig
        from ..tools.definitions.custom_tool_schema import CustomToolDefinition
        from ..tools.definitions.mcp_schema import MCPServerDefinition
    except Exception:  # noqa: BLE001 - schemas are best-effort extras
        logger.exception("Store schema imports failed; skipping schema render")
        return

    models = (
        ("hook_store", HookStore),
        ("trigger_store", TriggerStore),
        ("thread_config", ThreadConfig),
        ("custom_tool", CustomToolDefinition),
        ("mcp_server", MCPServerDefinition),
    )
    for name, model in models:
        try:
            schema = model.model_json_schema()
        except Exception:  # noqa: BLE001 - one bad schema must not sink the rest
            logger.exception("Failed to render %s schema", name)
            continue
        yield (
            f"{name}.schema.json",
            json.dumps(schema, indent=2, sort_keys=True) + "\n",
        )


def _write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only when it differs; report a write."""
    try:
        if path.exists() and path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass  # Unreadable existing file: fall through and rewrite it.
    path.write_text(content, encoding="utf-8")
    return True


def write_resource_map(root: Path | None = None) -> list[Path]:
    """Write README.md + schema/ into the resource root; return written paths.

    Best-effort: never raises (startup must not fail on a map write), logs
    per-file failures, skips everything if the root cannot be created.
    """
    from ..tools.execution_environment import resource_root

    base = root or resource_root()
    written: list[Path] = []
    try:
        base.mkdir(parents=True, exist_ok=True)
    except OSError:
        logger.exception("Resource root %s not writable; skipping map", base)
        return written

    targets: list[tuple[Path, str]] = [(base / "README.md", render_resource_readme())]
    schema_dir = base / "schema"
    try:
        schema_dir.mkdir(parents=True, exist_ok=True)
        targets += [(schema_dir / name, content) for name, content in _render_schemas()]
    except OSError:
        logger.exception("Schema dir %s not writable; writing README only", schema_dir)

    for path, content in targets:
        try:
            if _write_if_changed(path, content):
                written.append(path)
        except OSError:
            logger.exception("Failed to write resource map file %s", path)
    return written
