"""Workspace artifact download routes."""

from collections.abc import Callable
from pathlib import Path
from typing import Any
import mimetypes
import os

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse

from ...core.accounts import AuthenticatedUser


def create_workspace_router(require_admin_user: Callable[..., Any]) -> APIRouter:
    """Create the workspace router with the app's admin dependency injected."""
    router = APIRouter(tags=["Workspace"])

    @router.get("/workspace/download")
    async def download_workspace_file(
        path: str = Query(..., description="Absolute file path within the workspace"),
        _user: AuthenticatedUser = Depends(require_admin_user),
    ):
        """Download a file from the workspace directory.

        Admin-only because the workspace may contain artifacts generated by
        autonomous runs across users.
        """
        workspace_dir = Path(os.environ.get("NYMERIA_WORKSPACE_DIR", "/workspace")).resolve()
        resolved = Path(path).resolve()

        if not resolved.is_relative_to(workspace_dir):
            raise HTTPException(status_code=403, detail="Path outside workspace")
        if not resolved.is_file():
            raise HTTPException(status_code=404, detail="File not found")

        media_type = mimetypes.guess_type(str(resolved))[0] or "application/octet-stream"
        return FileResponse(
            path=str(resolved),
            media_type=media_type,
            filename=resolved.name,
        )

    return router
