"""Tests for the resource-filesystem-layout surface (backlog #75).

Slice 1: the resource_root() helper, the resource-root line injected into
the shell/file tool descriptions, and the generated data/README.md +
data/schema/ map artifacts.
"""

from __future__ import annotations

import json
from pathlib import Path

from nymeria.core.resource_map import render_resource_readme, write_resource_map
from nymeria.tools.bash import bash_execute
from nymeria.tools.execution_environment import (
    ExecutionEnvironment,
    configure_environment_aware_tool_descriptions,
    resource_root,
)
from nymeria.tools.file_edit import file_edit
from nymeria.tools.filesystem import file_read, file_write


class _Settings:
    def __init__(self, project_root: Path, data_dir: Path):
        self.project_root = project_root
        self.data_dir = data_dir


def _env(**overrides) -> ExecutionEnvironment:
    values = dict(
        platform_label="TestOS 1",
        default_cwd="/repo/root",
        process_cwd="/service",
        shell_executable="/bin/sh",
        available_shells=("bash", "sh"),
        in_container=False,
        path_separator="/",
        resource_root="/repo/root/data",
    )
    values.update(overrides)
    return ExecutionEnvironment(**values)


# ---------------------------------------------------------------------------
# resource_root()
# ---------------------------------------------------------------------------


def test_resource_root_resolves_data_dir(tmp_path, monkeypatch):
    data = tmp_path / "data"
    data.mkdir()
    monkeypatch.setattr(
        "nymeria.tools.execution_environment.get_settings",
        lambda: _Settings(tmp_path, data),
    )

    assert resource_root() == data.resolve()
    # v1 accepts and ignores the acting user (multi-user principle 5.1).
    assert resource_root("alice") == data.resolve()


def test_resource_root_falls_back_beside_default_cwd(tmp_path, monkeypatch):
    class _Broken:
        @property
        def project_root(self):
            return tmp_path

        @property
        def data_dir(self):
            raise RuntimeError("no data dir")

    monkeypatch.setattr(
        "nymeria.tools.execution_environment.get_settings",
        lambda: _Broken(),
    )

    assert resource_root() == (tmp_path / "data").resolve()


# ---------------------------------------------------------------------------
# Tool-description injection
# ---------------------------------------------------------------------------


def test_descriptions_include_resource_root_line():
    configure_environment_aware_tool_descriptions(
        [bash_execute, file_read, file_write, file_edit],
        _env(),
    )

    for tool in (bash_execute, file_read, file_write, file_edit):
        assert "Nymeria resource root" in (tool.description or "")
        assert "/repo/root/data" in (tool.description or "")
        assert "nymeria-resources" in (tool.description or "")


def test_descriptions_omit_resource_root_line_when_unknown():
    configure_environment_aware_tool_descriptions(
        [bash_execute, file_read],
        _env(resource_root=""),
    )

    assert "Nymeria resource root" not in (bash_execute.description or "")
    assert "Nymeria resource root" not in (file_read.description or "")


# ---------------------------------------------------------------------------
# Generated map artifacts
# ---------------------------------------------------------------------------


def test_write_resource_map_writes_readme_and_schemas(tmp_path):
    written = write_resource_map(tmp_path)

    names = {p.name for p in written}
    assert "README.md" in names
    for schema_name in (
        "hook_store.schema.json",
        "trigger_store.schema.json",
        "thread_config.schema.json",
        "custom_tool.schema.json",
        "mcp_server.schema.json",
    ):
        assert schema_name in names
        schema = json.loads((tmp_path / "schema" / schema_name).read_text())
        assert "properties" in schema

    readme = (tmp_path / "README.md").read_text(encoding="utf-8")
    assert readme == render_resource_readme()
    assert "custom_tools/<id>.json" in readme
    assert "hooks/<user>.json" in readme
    assert "nymeria-resources" in readme
    assert "Generated by Nymeria" in readme


def test_write_resource_map_is_write_if_changed(tmp_path):
    write_resource_map(tmp_path)
    readme = tmp_path / "README.md"
    first_mtime = readme.stat().st_mtime_ns

    assert write_resource_map(tmp_path) == []
    assert readme.stat().st_mtime_ns == first_mtime


def test_write_resource_map_regenerates_over_manual_edits(tmp_path):
    write_resource_map(tmp_path)
    readme = tmp_path / "README.md"
    readme.write_text("user scribbles\n", encoding="utf-8")

    written = write_resource_map(tmp_path)

    assert readme in written
    assert readme.read_text(encoding="utf-8") == render_resource_readme()


def test_readme_avoids_banned_punctuation():
    text = render_resource_readme()
    assert "—" not in text  # em dash
    for line in text.splitlines():
        if set(line) <= {"|", "-", " "}:
            continue  # markdown table separator row, not punctuation
        assert "--" not in line, line


# ---------------------------------------------------------------------------
# Slice 2: hot-load of external file edits
# ---------------------------------------------------------------------------


def _tool_json(tool_id: str, description: str = "demo tool") -> str:
    return json.dumps(
        {
            "id": tool_id,
            "name": tool_id,
            "description": description,
            "implementation_type": "http",
            "http_config": {"url": "https://example.com", "method": "GET"},
        }
    )


def _make_loader(tmp_path):
    from nymeria.core.custom_tools import CustomToolLoader

    loader = CustomToolLoader(tools_dir=tmp_path)
    loader.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    loader.load_all()
    return loader


def test_custom_tools_hot_load_add_edit_remove(tmp_path):
    loader = _make_loader(tmp_path)
    assert loader.get_definition("ext_demo") is None

    # Externally created file appears without load_all.
    (tmp_path / "ext_demo.json").write_text(_tool_json("ext_demo"), encoding="utf-8")
    defn = loader.get_definition("ext_demo")
    assert defn is not None and defn.description == "demo tool"
    assert loader.drain_registry_sync() == {"ext_demo"}
    assert loader.drain_registry_sync() == set()

    # Externally edited file re-parses.
    (tmp_path / "ext_demo.json").write_text(
        _tool_json("ext_demo", description="edited externally"), encoding="utf-8"
    )
    defn = loader.get_definition("ext_demo")
    assert defn is not None and defn.description == "edited externally"
    assert loader.drain_registry_sync() == {"ext_demo"}

    # Externally deleted file drops the definition.
    (tmp_path / "ext_demo.json").unlink()
    assert loader.get_definition("ext_demo") is None
    assert loader.drain_registry_sync() == {"ext_demo"}


def test_custom_tools_manager_writes_are_not_external_edits(tmp_path):
    from nymeria.tools.definitions.custom_tool_schema import CustomToolDefinition

    loader = _make_loader(tmp_path)
    definition = CustomToolDefinition(**json.loads(_tool_json("mine")))
    loader.save_definition(definition)

    assert loader.refresh_if_stale(force=True) == []
    assert loader.drain_registry_sync() == set()

    assert loader.delete_definition("mine") is True
    assert loader.refresh_if_stale(force=True) == []


def test_mcp_registry_hot_load_add_edit_remove(tmp_path):
    from nymeria.core.mcp_servers import MCPServerRegistry

    registry = MCPServerRegistry(servers_dir=tmp_path)
    registry.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    assert registry.get_server("srv") is None
    assert registry.drain_registry_sync() is False

    server_json = json.dumps(
        {"id": "srv", "name": "Srv", "transport": "http", "url": "https://example.com"}
    )
    (tmp_path / "srv.json").write_text(server_json, encoding="utf-8")
    defn = registry.get_server("srv")
    assert defn is not None and defn.url == "https://example.com"
    assert registry.drain_registry_sync() is True
    assert registry.drain_registry_sync() is False

    # Different content length: the (mtime_ns, size) fingerprint cannot rely
    # on mtime alone within the kernel's coarse timestamp granularity.
    (tmp_path / "srv.json").write_text(
        server_json.replace("https://example.com", "https://example.org/api"),
        encoding="utf-8",
    )
    defn = registry.get_server("srv")
    assert defn is not None and defn.url == "https://example.org/api"
    assert registry.drain_registry_sync() is True

    (tmp_path / "srv.json").unlink()
    assert registry.get_server("srv") is None
    assert registry.drain_registry_sync() is True


def _write_skill(root, name: str, description: str = "a demo skill", body: str = "Body v1"):
    skill_dir = root / name
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(
        f"---\nname: {name}\ndescription: {description}\n---\n\n{body}\n",
        encoding="utf-8",
    )
    return skill_dir


def _make_skill_manager(tmp_path, embedding_index=None):
    from nymeria.skills import SkillManager

    bundled = tmp_path / "bundled"
    data = tmp_path / "data-skills"
    bundled.mkdir()
    manager = SkillManager(bundled, data, embedding_index=embedding_index)
    manager.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    return manager, data


def test_skills_body_only_edit_hot_loads_via_get(tmp_path):
    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "demo-skill")
    manager.reload()
    skill = manager.get("demo-skill")
    assert skill is not None and "Body v1" in skill.body

    # Body-only raw edit: no reload() call anywhere.
    (skill_dir / "SKILL.md").write_text(
        "---\nname: demo-skill\ndescription: a demo skill\n---\n\nBody v2\n",
        encoding="utf-8",
    )
    skill = manager.get("demo-skill")
    assert skill is not None and "Body v2" in skill.body


def test_skills_external_add_and_remove_hot_load(tmp_path):
    manager, data = _make_skill_manager(tmp_path)

    skill_dir = _write_skill(data / "global", "late-skill")
    names = {s.name for s in manager.list_installed()}
    assert "late-skill" in names
    assert manager.get("late-skill") is not None

    import shutil

    shutil.rmtree(skill_dir)
    assert manager.get("late-skill") is None
    assert "late-skill" not in {s.name for s in manager.list_installed()}


def test_skills_corrupt_edit_serves_cached_copy_within_debounce(tmp_path):
    import time as _time

    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "fragile-skill")
    manager.reload()
    assert manager.get("fragile-skill") is not None

    # Pin the debounce window open: the scan-level rescan (which drops a
    # no-longer-parsing skill, matching load-time behavior) must not run, so
    # this exercises the per-skill _fresh_skill path serving the cached copy.
    manager.EXTERNAL_REFRESH_INTERVAL_SECONDS = 3600.0
    manager._last_freshness_check = _time.monotonic()

    (skill_dir / "SKILL.md").write_text("no frontmatter at all\n", encoding="utf-8")
    skill = manager.get("fragile-skill")
    assert skill is not None
    assert "Body v1" in skill.body  # cached copy, not the broken file

    # A full rescan drops the no-longer-parsing skill (scan skip behavior).
    manager.reload()
    assert manager.get("fragile-skill") is None


# ---------------------------------------------------------------------------
# Slice 3: fail-safe raw edits (uniform quarantine + secrets denylist)
# ---------------------------------------------------------------------------


def _quarantined(store_dir: Path, stem: str) -> list[Path]:
    return list((store_dir / "quarantine").glob(f"{stem}.corrupt-*"))


def test_trigger_store_corrupt_file_is_quarantined_not_overwritten(tmp_path):
    from nymeria.core.trigger_manager import TriggerManager

    manager = TriggerManager(tmp_path)
    path = manager.triggers_dir / "u1.json"
    corrupt = "{ not json"
    path.write_text(corrupt, encoding="utf-8")

    with manager.atomic_update("u1") as store:
        assert store.triggers == []

    assert not path.exists() or path.read_text(encoding="utf-8") != corrupt
    quarantined = _quarantined(manager.triggers_dir, "u1")
    assert len(quarantined) == 1
    assert quarantined[0].read_text(encoding="utf-8") == corrupt


def test_thread_config_corrupt_file_is_quarantined(tmp_path):
    from nymeria.core.thread_config import ThreadConfigManager

    manager = ThreadConfigManager(tmp_path)
    path = manager.configs_dir / "t1.json"
    corrupt = '{"thread_id": '
    path.write_text(corrupt, encoding="utf-8")

    assert manager.get_config("t1") is None
    quarantined = _quarantined(manager.configs_dir, "t1")
    assert len(quarantined) == 1
    assert quarantined[0].read_text(encoding="utf-8") == corrupt
    assert not path.exists()


def test_custom_tools_corrupt_file_is_quarantined_rest_loads(tmp_path):
    loader = _make_loader(tmp_path)
    (tmp_path / "good.json").write_text(_tool_json("good"), encoding="utf-8")
    (tmp_path / "bad.json").write_text("{ not json", encoding="utf-8")

    loader.refresh_if_stale(force=True)

    assert loader.get_definition("good") is not None
    assert len(_quarantined(tmp_path, "bad")) == 1
    assert not (tmp_path / "bad.json").exists()


def test_mcp_corrupt_file_is_quarantined(tmp_path):
    from nymeria.core.mcp_servers import MCPServerRegistry

    (tmp_path / "bad.json").write_text("[1, 2", encoding="utf-8")
    registry = MCPServerRegistry(servers_dir=tmp_path)

    assert registry.get_all_servers() == []
    assert len(_quarantined(tmp_path, "bad")) == 1


def test_skills_corrupt_file_is_skipped_not_quarantined(tmp_path):
    manager, data = _make_skill_manager(tmp_path)
    skill_dir = data / "global" / "broken-skill"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("no frontmatter\n", encoding="utf-8")

    manager.reload()

    assert manager.get("broken-skill") is None
    # Markdown skills fail soft: the file stays where the author left it.
    assert (skill_dir / "SKILL.md").exists()


def _patch_data_dir(monkeypatch, data_dir: Path):
    class _S:
        pass

    settings = _S()
    settings.data_dir = data_dir
    monkeypatch.setattr("nymeria.tools.filesystem.get_settings", lambda: settings)


def test_secrets_denylist_blocks_read_write_edit(tmp_path, monkeypatch):
    data_dir = tmp_path / "data"
    (data_dir / "auth_tokens" / "u1").mkdir(parents=True)
    (data_dir / "auth_tokens" / "u1" / "google.json").write_text("{}", encoding="utf-8")
    (data_dir / "accounts.db").write_text("sqlite", encoding="utf-8")
    (data_dir / "accounts.db-wal").write_text("wal", encoding="utf-8")
    _patch_data_dir(monkeypatch, data_dir)

    for target in (
        data_dir / "accounts.db",
        data_dir / "accounts.db-wal",
        data_dir / "auth_tokens" / "u1" / "google.json",
    ):
        content, _ = file_read.func(str(target))
        assert content.startswith("[Error]")
        assert "auth_write" in content

        write_result = file_write.func(str(target), "overwritten")
        assert write_result.startswith("[Error]")
        assert "auth_write" in write_result

        edit_result = file_edit.func(
            str(target),
            [{"operation": "replace", "old_text": "a", "new_text": "b"}],
        )
        assert '"type": "secrets_path"' in edit_result

    # Untouched: the denylist must not have altered the files.
    assert (data_dir / "accounts.db").read_text(encoding="utf-8") == "sqlite"
    assert (data_dir / "auth_tokens" / "u1" / "google.json").read_text(
        encoding="utf-8"
    ) == "{}"


def test_secrets_denylist_leaves_ordinary_data_files_alone(tmp_path, monkeypatch):
    data_dir = tmp_path / "data"
    (data_dir / "hooks").mkdir(parents=True)
    target = data_dir / "hooks" / "u1.json"
    target.write_text('{"hooks": []}', encoding="utf-8")
    _patch_data_dir(monkeypatch, data_dir)

    content, _ = file_read.func(str(target))
    assert content == '{"hooks": []}'
    assert file_write.func(str(target), '{"hooks": []}').startswith("[Success]")


# ---------------------------------------------------------------------------
# Slice 4: legible gate refusals + user-attributed external-edit audit
# ---------------------------------------------------------------------------


def test_python_gate_refusal_explains_raw_edits_and_next_step():
    from nymeria.core.python_custom_tools import (
        approve_python_revision,
        python_execution_gate,
    )
    from nymeria.tools.definitions.custom_tool_schema import PythonToolConfig

    config = PythonToolConfig(source_code="def run():\n    return 1\n")
    approved = approve_python_revision(config, {}, approved_by="admin-1")
    edited = approved.model_copy(
        update={"source_code": "def run():\n    return 2\n"}
    )
    refusal = python_execution_gate(edited, {})
    assert refusal is not None
    assert "changed since its approval" in refusal  # pinned substring
    assert "raw on-disk edits" in refusal
    assert "tool_create" in refusal
    assert "Next:" in refusal


def test_workflow_gate_refusal_explains_raw_edits_and_next_step():
    from nymeria.core.workflows.authoring import (
        approve_revision,
        workflow_execution_gate,
    )
    from nymeria.tools.definitions.custom_tool_schema import WorkflowToolConfig

    config = WorkflowToolConfig(source_code="def main(nym):\n    return 1\n")
    approved = approve_revision(config, {}, approved_by="admin-1")
    edited = approved.model_copy(
        update={"source_code": "def main(nym):\n    return 2\n"}
    )
    refusal = workflow_execution_gate(edited, {})
    assert refusal is not None
    assert "changed since its approval" in refusal  # pinned substring
    assert "raw on-disk edits" in refusal
    assert "Next:" in refusal


class _AuditRecorder:
    def __init__(self):
        self.records = []

    def __call__(self, store, detail, *, user_id="default"):
        self.records.append((store, detail, user_id))


def test_store_fingerprint_sidecar_roundtrip(tmp_path):
    from nymeria.core.storage_paths import (
        read_store_fingerprint,
        record_store_fingerprint,
        store_fingerprint_path,
    )

    target = tmp_path / "store.json"
    assert read_store_fingerprint(target) is None  # absent sidecar: fail-safe
    target.write_text("{}", encoding="utf-8")
    sig = record_store_fingerprint(target)
    st = target.stat()
    assert sig == (st.st_mtime_ns, st.st_size)
    assert read_store_fingerprint(target) == sig

    # A corrupt sidecar reads as None instead of raising.
    store_fingerprint_path(target).write_text("not-a-sig", encoding="utf-8")
    assert read_store_fingerprint(target) is None

    # Recording for a missing store drops the stale sidecar.
    record_store_fingerprint(target)
    target.unlink()
    assert record_store_fingerprint(target) is None
    assert not store_fingerprint_path(target).exists()


def test_hooks_external_edit_is_audited_user_attributed(tmp_path, monkeypatch):
    """Cross-instance: authoring writes via its own manager (the tools/REST
    singletons in production), the engine reads via a separate instance. The
    shared .sig sidecar is what lets the reader tell manager writes from raw
    on-disk edits."""
    from nymeria.core.hook_manager import HookManager

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    author = HookManager(tmp_path)  # the tools/REST authoring instance
    reader = HookManager(tmp_path)  # the engine instance (never saves)
    author.add_hook("u1", name="n", event="done", text="hi")
    reader.get_hooks_cached("u1")
    assert recorder.records == []  # cross-instance manager write: no audit

    author.add_hook("u1", name="n2", event="done", text="hi2")
    reader.get_hooks_cached("u1")
    assert recorder.records == []  # subsequent manager writes: still no audit

    # Raw on-disk edit. No utime bump: the appended byte changes st_size, and
    # size is part of both the read-cache key and the fingerprint, so the
    # edit is seen even when the kernel's coarse timestamp clock gives it the
    # same mtime_ns as the manager save.
    path = reader._path_for("u1")
    path.write_text(path.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    reader.get_hooks_cached("u1")
    assert ("hooks", "hook store file edited on disk", "u1") in recorder.records

    # Acknowledged in the shared sidecar: audited once, across instances.
    count = len(recorder.records)
    reader.get_hooks_cached("u1")
    HookManager(tmp_path).get_hooks_cached("u1")
    assert len(recorder.records) == count


def test_triggers_external_edit_is_audited_once(tmp_path, monkeypatch):
    """Cross-instance: fire-state saves happen in the ticker's manager (a
    separate process in the Docker shape) while authoring goes through the
    tool/REST managers. Neither side's saves may audit as external."""
    from nymeria.core.trigger_manager import TriggerManager, TriggerStore

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    ticker_side = TriggerManager(tmp_path)  # the ticker's instance
    authoring = TriggerManager(tmp_path)  # the tool/REST authoring instance
    ticker_side._save(TriggerStore(user_id="u1"))
    authoring._load("u1")
    assert recorder.records == []  # cross-instance manager write: no audit

    authoring._save(TriggerStore(user_id="u1"))
    ticker_side._load("u1")
    assert recorder.records == []  # and in the other direction

    path = ticker_side.triggers_dir / "u1.json"
    path.write_text(path.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    ticker_side._load("u1")
    assert ("triggers", "trigger store file edited on disk", "u1") in recorder.records

    # Acknowledged in the shared sidecar: once, not per poll or per instance.
    count = len(recorder.records)
    ticker_side._load("u1")
    authoring._load("u1")
    assert len(recorder.records) == count


def test_custom_tools_external_edit_is_audited(tmp_path, monkeypatch):
    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    loader = _make_loader(tmp_path)
    (tmp_path / "audited.json").write_text(_tool_json("audited"), encoding="utf-8")
    loader.refresh_if_stale(force=True)

    assert any(
        store == "custom_tools" and "audited" in detail
        for store, detail, _user in recorder.records
    )


def test_skills_external_edit_triggers_background_index_rebuild(tmp_path):
    import time as _time

    class _FakeIndex:
        def __init__(self):
            self.rebuilds = 0

        def rebuild(self, namespace, items):
            self.rebuilds += 1
            return {"fts_indexed": len(items), "semantic_indexed": 0}

    index = _FakeIndex()
    manager, data = _make_skill_manager(tmp_path, embedding_index=index)
    baseline = index.rebuilds  # init reload() rebuilds inline

    _write_skill(data / "global", "indexed-skill")
    assert manager.refresh_if_stale(force=True) is True

    deadline = _time.monotonic() + 5.0
    while index.rebuilds <= baseline and _time.monotonic() < deadline:
        _time.sleep(0.01)
    assert index.rebuilds > baseline
