"""Tests for the resource-filesystem-layout surface (backlog #75).

Slice 1: the resource_root() helper, the resource-root line injected into
the shell/file tool descriptions, and the generated data/README.md +
data/schema/ map artifacts.
"""

from __future__ import annotations

import errno
import json
import os
import stat
import time
from pathlib import Path

from nymeria.core.resource_map import render_resource_readme, write_resource_map
from nymeria.tools.bash import bash_execute
from nymeria.tools.execution_environment import (
    ExecutionEnvironment,
    configure_environment_aware_tool_descriptions,
    resource_root,
)
from nymeria.tools.file_edit import file_edit
from nymeria.tools.filesystem import file_read, file_write


class _Settings:
    def __init__(self, project_root: Path, data_dir: Path):
        self.project_root = project_root
        self.data_dir = data_dir


def _env(**overrides) -> ExecutionEnvironment:
    values = dict(
        platform_label="TestOS 1",
        default_cwd="/repo/root",
        process_cwd="/service",
        shell_executable="/bin/sh",
        available_shells=("bash", "sh"),
        in_container=False,
        path_separator="/",
        resource_root="/repo/root/data",
    )
    values.update(overrides)
    return ExecutionEnvironment(**values)


# ---------------------------------------------------------------------------
# resource_root()
# ---------------------------------------------------------------------------


def test_resource_root_resolves_data_dir(tmp_path, monkeypatch):
    data = tmp_path / "data"
    data.mkdir()
    monkeypatch.setattr(
        "nymeria.tools.execution_environment.get_settings",
        lambda: _Settings(tmp_path, data),
    )

    assert resource_root() == data.resolve()
    # v1 accepts and ignores the acting user (multi-user principle 5.1).
    assert resource_root("alice") == data.resolve()


def test_resource_root_falls_back_beside_default_cwd(tmp_path, monkeypatch):
    class _Broken:
        @property
        def project_root(self):
            return tmp_path

        @property
        def data_dir(self):
            raise RuntimeError("no data dir")

    monkeypatch.setattr(
        "nymeria.tools.execution_environment.get_settings",
        lambda: _Broken(),
    )

    assert resource_root() == (tmp_path / "data").resolve()


# ---------------------------------------------------------------------------
# Tool-description injection
# ---------------------------------------------------------------------------


def test_descriptions_include_resource_root_line():
    configure_environment_aware_tool_descriptions(
        [bash_execute, file_read, file_write, file_edit],
        _env(),
    )

    for tool in (bash_execute, file_read, file_write, file_edit):
        assert "Nymeria resource root" in (tool.description or "")
        assert "/repo/root/data" in (tool.description or "")
        assert "nymeria-resources" in (tool.description or "")


def test_descriptions_omit_resource_root_line_when_unknown():
    configure_environment_aware_tool_descriptions(
        [bash_execute, file_read],
        _env(resource_root=""),
    )

    assert "Nymeria resource root" not in (bash_execute.description or "")
    assert "Nymeria resource root" not in (file_read.description or "")


# ---------------------------------------------------------------------------
# Generated map artifacts
# ---------------------------------------------------------------------------


def test_write_resource_map_writes_readme_and_schemas(tmp_path):
    written = write_resource_map(tmp_path)

    names = {p.name for p in written}
    assert "README.md" in names
    for schema_name in (
        "hook_store.schema.json",
        "trigger_store.schema.json",
        "thread_config.schema.json",
        "custom_tool.schema.json",
        "mcp_server.schema.json",
    ):
        assert schema_name in names
        schema = json.loads((tmp_path / "schema" / schema_name).read_text())
        assert "properties" in schema

    readme = (tmp_path / "README.md").read_text(encoding="utf-8")
    assert readme == render_resource_readme()
    assert "custom_tools/<id>.json" in readme
    assert "hooks/<user>.json" in readme
    assert "nymeria-resources" in readme
    assert "Generated by Nymeria" in readme


def test_write_resource_map_is_write_if_changed(tmp_path):
    write_resource_map(tmp_path)
    readme = tmp_path / "README.md"
    first_mtime = readme.stat().st_mtime_ns

    assert write_resource_map(tmp_path) == []
    assert readme.stat().st_mtime_ns == first_mtime


def test_write_resource_map_regenerates_over_manual_edits(tmp_path):
    write_resource_map(tmp_path)
    readme = tmp_path / "README.md"
    readme.write_text("user scribbles\n", encoding="utf-8")

    written = write_resource_map(tmp_path)

    assert readme in written
    assert readme.read_text(encoding="utf-8") == render_resource_readme()


def test_readme_avoids_banned_punctuation():
    text = render_resource_readme()
    assert "—" not in text  # em dash
    for line in text.splitlines():
        if set(line) <= {"|", "-", " "}:
            continue  # markdown table separator row, not punctuation
        assert "--" not in line, line


# ---------------------------------------------------------------------------
# Slice 2: hot-load of external file edits
# ---------------------------------------------------------------------------


def _tool_json(tool_id: str, description: str = "demo tool") -> str:
    return json.dumps(
        {
            "id": tool_id,
            "name": tool_id,
            "description": description,
            "implementation_type": "http",
            "http_config": {"url": "https://example.com", "method": "GET"},
        }
    )


def _make_loader(tmp_path):
    from nymeria.core.custom_tools import CustomToolLoader

    loader = CustomToolLoader(tools_dir=tmp_path)
    loader.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    loader.load_all()
    return loader


def test_custom_tools_hot_load_add_edit_remove(tmp_path):
    loader = _make_loader(tmp_path)
    assert loader.get_definition("ext_demo") is None

    # Externally created file appears without load_all.
    (tmp_path / "ext_demo.json").write_text(_tool_json("ext_demo"), encoding="utf-8")
    defn = loader.get_definition("ext_demo")
    assert defn is not None and defn.description == "demo tool"
    assert loader.drain_registry_sync() == {"ext_demo"}
    assert loader.drain_registry_sync() == set()

    # Externally edited file re-parses.
    (tmp_path / "ext_demo.json").write_text(
        _tool_json("ext_demo", description="edited externally"), encoding="utf-8"
    )
    defn = loader.get_definition("ext_demo")
    assert defn is not None and defn.description == "edited externally"
    assert loader.drain_registry_sync() == {"ext_demo"}

    # Externally deleted file drops the definition.
    (tmp_path / "ext_demo.json").unlink()
    assert loader.get_definition("ext_demo") is None
    assert loader.drain_registry_sync() == {"ext_demo"}


def test_custom_tools_manager_writes_are_not_external_edits(tmp_path):
    from nymeria.tools.definitions.custom_tool_schema import CustomToolDefinition

    loader = _make_loader(tmp_path)
    definition = CustomToolDefinition(**json.loads(_tool_json("mine")))
    loader.save_definition(definition)

    assert loader.refresh_if_stale(force=True) == []
    assert loader.drain_registry_sync() == set()

    assert loader.delete_definition("mine") is True
    assert loader.refresh_if_stale(force=True) == []


def test_mcp_registry_hot_load_add_edit_remove(tmp_path):
    from nymeria.core.mcp_servers import MCPServerRegistry

    registry = MCPServerRegistry(servers_dir=tmp_path)
    registry.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    assert registry.get_server("srv") is None
    assert registry.drain_registry_sync() is False

    server_json = json.dumps(
        {"id": "srv", "name": "Srv", "transport": "http", "url": "https://example.com"}
    )
    (tmp_path / "srv.json").write_text(server_json, encoding="utf-8")
    defn = registry.get_server("srv")
    assert defn is not None and defn.url == "https://example.com"
    assert registry.drain_registry_sync() is True
    assert registry.drain_registry_sync() is False

    # Different content length: the (mtime_ns, size) fingerprint cannot rely
    # on mtime alone within the kernel's coarse timestamp granularity.
    (tmp_path / "srv.json").write_text(
        server_json.replace("https://example.com", "https://example.org/api"),
        encoding="utf-8",
    )
    defn = registry.get_server("srv")
    assert defn is not None and defn.url == "https://example.org/api"
    assert registry.drain_registry_sync() is True

    (tmp_path / "srv.json").unlink()
    assert registry.get_server("srv") is None
    assert registry.drain_registry_sync() is True


def _write_skill(root, name: str, description: str = "a demo skill", body: str = "Body v1"):
    skill_dir = root / name
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(
        f"---\nname: {name}\ndescription: {description}\n---\n\n{body}\n",
        encoding="utf-8",
    )
    return skill_dir


def _make_skill_manager(tmp_path, embedding_index=None):
    from nymeria.skills import SkillManager

    bundled = tmp_path / "bundled"
    data = tmp_path / "data-skills"
    bundled.mkdir()
    manager = SkillManager(bundled, data, embedding_index=embedding_index)
    manager.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    return manager, data


def test_skills_body_only_edit_hot_loads_via_get(tmp_path):
    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "demo-skill")
    manager.reload()
    skill = manager.get("demo-skill")
    assert skill is not None and "Body v1" in skill.body

    # Body-only raw edit: no reload() call anywhere.
    (skill_dir / "SKILL.md").write_text(
        "---\nname: demo-skill\ndescription: a demo skill\n---\n\nBody v2\n",
        encoding="utf-8",
    )
    skill = manager.get("demo-skill")
    assert skill is not None and "Body v2" in skill.body


def test_skills_external_add_and_remove_hot_load(tmp_path):
    manager, data = _make_skill_manager(tmp_path)

    skill_dir = _write_skill(data / "global", "late-skill")
    names = {s.name for s in manager.list_installed()}
    assert "late-skill" in names
    assert manager.get("late-skill") is not None

    import shutil

    shutil.rmtree(skill_dir)
    assert manager.get("late-skill") is None
    assert "late-skill" not in {s.name for s in manager.list_installed()}


def test_skills_corrupt_edit_serves_cached_copy_within_debounce(tmp_path):
    import time as _time

    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "fragile-skill")
    manager.reload()
    assert manager.get("fragile-skill") is not None

    # Pin the debounce window open: the scan-level rescan (which drops a
    # no-longer-parsing skill, matching load-time behavior) must not run, so
    # this exercises the per-skill _fresh_skill path serving the cached copy.
    manager.EXTERNAL_REFRESH_INTERVAL_SECONDS = 3600.0
    manager._last_freshness_check = _time.monotonic()

    (skill_dir / "SKILL.md").write_text("no frontmatter at all\n", encoding="utf-8")
    skill = manager.get("fragile-skill")
    assert skill is not None
    assert "Body v1" in skill.body  # cached copy, not the broken file

    # A full rescan drops the no-longer-parsing skill (scan skip behavior).
    manager.reload()
    assert manager.get("fragile-skill") is None


# ---------------------------------------------------------------------------
# Slice 3: fail-safe raw edits (uniform quarantine + secrets denylist)
# ---------------------------------------------------------------------------


def _quarantined(store_dir: Path, stem: str) -> list[Path]:
    return list((store_dir / "quarantine").glob(f"{stem}.corrupt-*"))


def test_trigger_store_corrupt_file_is_quarantined_not_overwritten(tmp_path):
    from nymeria.core.trigger_manager import TriggerManager

    manager = TriggerManager(tmp_path)
    path = manager.triggers_dir / "u1.json"
    corrupt = "{ not json"
    path.write_text(corrupt, encoding="utf-8")

    with manager.atomic_update("u1") as store:
        assert store.triggers == []

    assert not path.exists() or path.read_text(encoding="utf-8") != corrupt
    quarantined = _quarantined(manager.triggers_dir, "u1")
    assert len(quarantined) == 1
    assert quarantined[0].read_text(encoding="utf-8") == corrupt


def test_thread_config_corrupt_file_is_quarantined(tmp_path):
    from nymeria.core.thread_config import ThreadConfigManager

    manager = ThreadConfigManager(tmp_path)
    path = manager.configs_dir / "t1.json"
    corrupt = '{"thread_id": '
    path.write_text(corrupt, encoding="utf-8")

    assert manager.get_config("t1") is None
    quarantined = _quarantined(manager.configs_dir, "t1")
    assert len(quarantined) == 1
    assert quarantined[0].read_text(encoding="utf-8") == corrupt
    assert not path.exists()


def test_custom_tools_corrupt_file_is_quarantined_rest_loads(tmp_path):
    loader = _make_loader(tmp_path)
    (tmp_path / "good.json").write_text(_tool_json("good"), encoding="utf-8")
    (tmp_path / "bad.json").write_text("{ not json", encoding="utf-8")

    loader.refresh_if_stale(force=True)

    assert loader.get_definition("good") is not None
    assert len(_quarantined(tmp_path, "bad")) == 1
    assert not (tmp_path / "bad.json").exists()


def test_mcp_corrupt_file_is_quarantined(tmp_path):
    from nymeria.core.mcp_servers import MCPServerRegistry

    (tmp_path / "bad.json").write_text("[1, 2", encoding="utf-8")
    registry = MCPServerRegistry(servers_dir=tmp_path)

    assert registry.get_all_servers() == []
    assert len(_quarantined(tmp_path, "bad")) == 1


def test_skills_corrupt_file_is_skipped_not_quarantined(tmp_path):
    manager, data = _make_skill_manager(tmp_path)
    skill_dir = data / "global" / "broken-skill"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("no frontmatter\n", encoding="utf-8")

    manager.reload()

    assert manager.get("broken-skill") is None
    # Markdown skills fail soft: the file stays where the author left it.
    assert (skill_dir / "SKILL.md").exists()


def _require_unprivileged_posix(what: str) -> None:
    """Skip a test whose subject is POSIX permission enforcement.

    Two ways it does not apply: Windows has no ``geteuid`` at all (and none of
    the mode semantics these pin), and root bypasses the bits outright, which
    is how the Docker containers run.
    """
    import pytest

    if os.name != "posix":
        pytest.skip(f"{what} are POSIX semantics")
    if os.geteuid() == 0:
        pytest.skip(f"root bypasses {what}")


def _patch_data_dir(monkeypatch, data_dir: Path):
    class _S:
        pass

    settings = _S()
    settings.data_dir = data_dir
    monkeypatch.setattr("nymeria.tools.filesystem.get_settings", lambda: settings)


def test_secrets_denylist_blocks_read_write_edit(tmp_path, monkeypatch):
    data_dir = tmp_path / "data"
    (data_dir / "auth_tokens" / "u1").mkdir(parents=True)
    (data_dir / "auth_tokens" / "u1" / "google.json").write_text("{}", encoding="utf-8")
    (data_dir / "accounts.db").write_text("sqlite", encoding="utf-8")
    (data_dir / "accounts.db-wal").write_text("wal", encoding="utf-8")
    _patch_data_dir(monkeypatch, data_dir)

    for target in (
        data_dir / "accounts.db",
        data_dir / "accounts.db-wal",
        data_dir / "auth_tokens" / "u1" / "google.json",
    ):
        content, _ = file_read.func(str(target))
        assert content.startswith("[Error]")
        assert "auth_write" in content

        write_result = file_write.func(str(target), "overwritten")
        assert write_result.startswith("[Error]")
        assert "auth_write" in write_result

        edit_result = file_edit.func(
            str(target),
            [{"operation": "replace", "old_text": "a", "new_text": "b"}],
        )
        assert '"type": "secrets_path"' in edit_result

    # Untouched: the denylist must not have altered the files.
    assert (data_dir / "accounts.db").read_text(encoding="utf-8") == "sqlite"
    assert (data_dir / "auth_tokens" / "u1" / "google.json").read_text(
        encoding="utf-8"
    ) == "{}"


def test_secrets_denylist_leaves_ordinary_data_files_alone(tmp_path, monkeypatch):
    data_dir = tmp_path / "data"
    (data_dir / "hooks").mkdir(parents=True)
    target = data_dir / "hooks" / "u1.json"
    target.write_text('{"hooks": []}', encoding="utf-8")
    _patch_data_dir(monkeypatch, data_dir)

    content, _ = file_read.func(str(target))
    assert content == '{"hooks": []}'
    assert file_write.func(str(target), '{"hooks": []}').startswith("[Success]")


def test_file_write_overwrite_is_atomic_and_preserves_semantics(tmp_path, monkeypatch):
    """Overwrites go through temp-plus-rename so a torn file can never reach
    the store loaders (which would quarantine it, losing the good bytes).
    The rename must not cost the two things a plain write gave for free:
    the file's permission bits, and writing THROUGH a symlink."""
    data_dir = tmp_path / "data"
    data_dir.mkdir(parents=True)
    _patch_data_dir(monkeypatch, data_dir)

    target = tmp_path / "script.sh"
    target.write_text("old\n", encoding="utf-8")
    target.chmod(0o750)
    assert file_write.func(str(target), "new\n").startswith("[Success]")
    assert target.read_text(encoding="utf-8") == "new\n"
    assert stat.S_IMODE(target.stat().st_mode) == 0o750  # mode survived

    # Writing through a symlink updates the target, not the link itself.
    link = tmp_path / "link.txt"
    link.symlink_to(target)
    assert file_write.func(str(link), "via link\n").startswith("[Success]")
    assert link.is_symlink()
    assert target.read_text(encoding="utf-8") == "via link\n"

    # No temp files left behind on the happy path.
    assert [p.name for p in tmp_path.glob("*.tmp")] == []

    # Appends stay in place (there is no atomic append).
    assert file_write.func(str(target), "more\n", append=True).startswith("[Success]")
    assert target.read_text(encoding="utf-8") == "via link\nmore\n"


def test_file_write_falls_back_when_the_directory_is_not_writable(tmp_path, monkeypatch):
    """A rename needs write permission on the DIRECTORY; a plain write needs it
    on the file. So making writes atomic silently narrowed what file_write can
    do: a writable file in a read-only directory (a mounted config dir, a
    sticky shared dir) used to work and must keep working."""
    _require_unprivileged_posix("directory permission bits")

    data_dir = tmp_path / "data"
    data_dir.mkdir(parents=True)
    _patch_data_dir(monkeypatch, data_dir)

    locked = tmp_path / "locked"
    locked.mkdir()
    target = locked / "config.txt"
    target.write_text("old\n", encoding="utf-8")
    locked.chmod(0o555)
    try:
        assert file_write.func(str(target), "new\n").startswith("[Success]")
        assert target.read_text(encoding="utf-8") == "new\n"
        assert list(locked.glob("*.tmp")) == []
    finally:
        locked.chmod(0o755)  # so tmp_path teardown can clean up


def test_file_write_does_not_truncate_when_the_disk_is_full(tmp_path, monkeypatch):
    """A full disk raises OSError too, and there the atomic attempt failed
    SAFELY with the target intact. Falling back would open it "w", truncate
    it, and then fail as well, turning a clean failure into data loss on the
    very store files the atomic write exists to protect."""
    data_dir = tmp_path / "data"
    data_dir.mkdir(parents=True)
    _patch_data_dir(monkeypatch, data_dir)

    target = tmp_path / "store.json"
    target.write_text("important\n", encoding="utf-8")

    def _no_space(path, content, *, encoding="utf-8"):
        raise OSError(errno.ENOSPC, "No space left on device")

    monkeypatch.setattr("nymeria.tools.filesystem.write_text_atomic", _no_space)
    result = file_write.func(str(target), "new\n")

    assert not result.startswith("[Success]")
    assert target.read_text(encoding="utf-8") == "important\n"  # not truncated


def test_file_write_keeps_read_only_files_read_only(tmp_path, monkeypatch):
    """The inverse: a rename would REPLACE a chmod 444 file, so an atomic
    write would quietly grant a write the OS was refusing."""
    _require_unprivileged_posix("file permission bits")

    data_dir = tmp_path / "data"
    data_dir.mkdir(parents=True)
    _patch_data_dir(monkeypatch, data_dir)

    target = tmp_path / "readonly.txt"
    target.write_text("old\n", encoding="utf-8")
    target.chmod(0o444)

    result = file_write.func(str(target), "new\n")
    assert not result.startswith("[Success]")
    assert target.read_text(encoding="utf-8") == "old\n"


# ---------------------------------------------------------------------------
# Slice 4: legible gate refusals + user-attributed external-edit audit
# ---------------------------------------------------------------------------


def test_python_gate_refusal_explains_raw_edits_and_next_step():
    from nymeria.core.python_custom_tools import (
        approve_python_revision,
        python_execution_gate,
    )
    from nymeria.tools.definitions.custom_tool_schema import PythonToolConfig

    config = PythonToolConfig(source_code="def run():\n    return 1\n")
    approved = approve_python_revision(config, {}, approved_by="admin-1")
    edited = approved.model_copy(
        update={"source_code": "def run():\n    return 2\n"}
    )
    refusal = python_execution_gate(edited, {})
    assert refusal is not None
    assert "changed since its approval" in refusal  # pinned substring
    assert "raw on-disk edits" in refusal
    assert "tool_create" in refusal
    assert "Next:" in refusal


def test_workflow_gate_refusal_explains_raw_edits_and_next_step():
    from nymeria.core.workflows.authoring import (
        approve_revision,
        workflow_execution_gate,
    )
    from nymeria.tools.definitions.custom_tool_schema import WorkflowToolConfig

    config = WorkflowToolConfig(source_code="def main(nym):\n    return 1\n")
    approved = approve_revision(config, {}, approved_by="admin-1")
    edited = approved.model_copy(
        update={"source_code": "def main(nym):\n    return 2\n"}
    )
    refusal = workflow_execution_gate(edited, {})
    assert refusal is not None
    assert "changed since its approval" in refusal  # pinned substring
    assert "raw on-disk edits" in refusal
    assert "Next:" in refusal


class _AuditRecorder:
    def __init__(self):
        self.records = []

    def __call__(self, store, detail, *, user_id="default"):
        self.records.append((store, detail, user_id))


def test_store_fingerprint_sidecar_roundtrip(tmp_path):
    from nymeria.core.storage_paths import (
        read_store_fingerprint,
        record_store_fingerprint,
        store_fingerprint_path,
    )

    target = tmp_path / "store.json"
    assert read_store_fingerprint(target) is None  # absent sidecar: fail-safe
    target.write_text("{}", encoding="utf-8")
    sig = record_store_fingerprint(target)
    st = target.stat()
    # Recorded straight after a write, so the file is racy and the fingerprint
    # carries a content hash: that is what lets a reader in another process
    # tell a raw edit from this write when both share a coarse mtime tick.
    assert sig[:2] == (st.st_mtime_ns, st.st_size)
    assert sig[2] and len(sig[2]) == 64
    assert read_store_fingerprint(target) == sig

    # A corrupt sidecar reads as None instead of raising.
    store_fingerprint_path(target).write_text("not-a-sig", encoding="utf-8")
    assert read_store_fingerprint(target) is None

    # Legacy two-field sidecars predate the content hash and still exist on
    # deployed hosts: they must parse (with an empty hash) rather than read as
    # "no manager write on record", which would silently disable the audit.
    store_fingerprint_path(target).write_text(
        f"{sig[0]}:{sig[1]}\n", encoding="utf-8"
    )
    assert read_store_fingerprint(target) == (sig[0], sig[1], "")

    # Recording for a missing store drops the stale sidecar.
    record_store_fingerprint(target)
    target.unlink()
    assert record_store_fingerprint(target) is None
    assert not store_fingerprint_path(target).exists()


def test_store_fingerprint_sidecar_roundtrips_a_hashless_fingerprint(tmp_path):
    """The other sidecar shape: a fingerprint recorded for a QUIET file.

    Loaders re-record after acknowledging a raw edit, and an edit is often
    discovered long after it happened, so the recorded fingerprint carries no
    hash. The wire format has to round-trip that empty third field rather than
    reading back as a corrupt sidecar (which fails safe by disabling the audit,
    so the loss would be silent).
    """
    from nymeria.core.storage_paths import (
        RACY_FINGERPRINT_MARGIN_NS,
        compare_fingerprint,
        read_store_fingerprint,
        record_store_fingerprint,
    )

    target = tmp_path / "store.json"
    target.write_text("{}", encoding="utf-8")
    quiet = time.time_ns() - RACY_FINGERPRINT_MARGIN_NS * 2
    os.utime(target, ns=(quiet, quiet))

    sig = record_store_fingerprint(target)
    assert sig is not None and sig[2] == ""  # quiet file: mtime is trusted
    assert read_store_fingerprint(target) == sig

    # A hashless baseline still answers both questions correctly.
    _, changed = compare_fingerprint(target, sig)
    assert changed is False
    target.write_text("[]", encoding="utf-8")  # same size, later tick
    os.utime(target, ns=(quiet + 1_000_000, quiet + 1_000_000))
    _, changed = compare_fingerprint(target, sig)
    assert changed is True


def test_hooks_external_edit_is_audited_user_attributed(tmp_path, monkeypatch):
    """Cross-instance: authoring writes via its own manager (the tools/REST
    singletons in production), the engine reads via a separate instance. The
    shared .sig sidecar is what lets the reader tell manager writes from raw
    on-disk edits."""
    from nymeria.core.hook_manager import HookManager

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    author = HookManager(tmp_path)  # the tools/REST authoring instance
    reader = HookManager(tmp_path)  # the engine instance (never saves)
    author.add_hook("u1", name="n", event="done", text="hi")
    reader.get_hooks_cached("u1")
    assert recorder.records == []  # cross-instance manager write: no audit

    author.add_hook("u1", name="n2", event="done", text="hi2")
    reader.get_hooks_cached("u1")
    assert recorder.records == []  # subsequent manager writes: still no audit

    # Raw on-disk edit. No utime bump: the appended byte changes st_size, and
    # size is part of both the read-cache key and the fingerprint, so the
    # edit is seen even when the kernel's coarse timestamp clock gives it the
    # same mtime_ns as the manager save.
    path = reader._path_for("u1")
    path.write_text(path.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    reader.get_hooks_cached("u1")
    assert ("hooks", "hook store file edited on disk", "u1") in recorder.records

    # Acknowledged in the shared sidecar: audited once, across instances.
    count = len(recorder.records)
    reader.get_hooks_cached("u1")
    HookManager(tmp_path).get_hooks_cached("u1")
    assert len(recorder.records) == count


def test_triggers_external_edit_is_audited_once(tmp_path, monkeypatch):
    """Cross-instance: fire-state saves happen in the ticker's manager (a
    separate process in the Docker shape) while authoring goes through the
    tool/REST managers. Neither side's saves may audit as external."""
    from nymeria.core.trigger_manager import TriggerManager, TriggerStore

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    ticker_side = TriggerManager(tmp_path)  # the ticker's instance
    authoring = TriggerManager(tmp_path)  # the tool/REST authoring instance
    ticker_side._save(TriggerStore(user_id="u1"))
    authoring._load("u1")
    assert recorder.records == []  # cross-instance manager write: no audit

    authoring._save(TriggerStore(user_id="u1"))
    ticker_side._load("u1")
    assert recorder.records == []  # and in the other direction

    path = ticker_side.triggers_dir / "u1.json"
    path.write_text(path.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    ticker_side._load("u1")
    assert ("triggers", "trigger store file edited on disk", "u1") in recorder.records

    # Acknowledged in the shared sidecar: once, not per poll or per instance.
    count = len(recorder.records)
    ticker_side._load("u1")
    authoring._load("u1")
    assert len(recorder.records) == count


def test_triggers_deletion_is_not_audited_as_an_edit(tmp_path, monkeypatch):
    """A store file that vanishes between the exists() check and the stat is
    "changed" from the sidecar's point of view, but logging a raw EDIT for a
    deletion fabricates an audit record, which this machinery treats as the
    worse failure. The hooks and teams readers guard it; triggers must too."""
    from nymeria.core.trigger_manager import TriggerManager, TriggerStore

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    manager = TriggerManager(tmp_path)
    manager._save(TriggerStore(user_id="u1"))
    path = manager.triggers_dir / "u1.json"

    real_exists = Path.exists

    def _vanish(self):
        present = real_exists(self)
        if present and self == path:
            path.unlink()  # removed after the check, before the stat
        return present

    monkeypatch.setattr(Path, "exists", _vanish)
    manager._load("u1")

    # The read that follows still fails and reports its own unreadable-store
    # line; what must NOT appear is a raw-EDIT claim about a deleted file.
    assert not [r for r in recorder.records if "edited on disk" in r[1]]


def test_legacy_two_field_sidecar_upgrades_without_a_spurious_audit(tmp_path, monkeypatch):
    """The deployed-host upgrade path, end to end.

    Hosts running before the hash existed have two-field sidecars on disk. If
    those parsed as "no sidecar" the audit would silently switch off; if they
    parsed as a mismatch every store would audit itself as externally edited
    on the first read after upgrade. Neither is acceptable, and both are silent.
    """
    from nymeria.core.hook_manager import HookManager

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    author = HookManager(tmp_path)
    author.add_hook("u1", name="original", event="done", text="hi")
    path = author.hooks_dir / "u1.json"
    sidecar = path.with_name(path.name + ".sig")

    # Rewrite the sidecar in the pre-hash format, as an upgraded host has it.
    st = path.stat()
    sidecar.write_text(f"{st.st_mtime_ns}:{st.st_size}\n", encoding="utf-8")

    reader = HookManager(tmp_path)
    assert [h.name for h in reader.get_hooks_cached("u1")] == ["original"]
    assert recorder.records == []  # not audited as an edit by the format change

    # A genuine raw edit against the legacy baseline is still caught, and the
    # acknowledgement is written back in the new three-field format.
    path.write_text(path.read_text(encoding="utf-8").replace("original", "renamed"), encoding="utf-8")
    fresh = HookManager(tmp_path)
    assert [h.name for h in fresh.get_hooks_cached("u1")] == ["renamed"]
    assert [r[0] for r in recorder.records] == ["hooks"]
    assert sidecar.read_text(encoding="utf-8").count(":") == 2


def test_custom_tools_external_edit_is_audited(tmp_path, monkeypatch):
    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    loader = _make_loader(tmp_path)
    (tmp_path / "audited.json").write_text(_tool_json("audited"), encoding="utf-8")
    loader.refresh_if_stale(force=True)

    assert any(
        store == "custom_tools" and "audited" in detail
        for store, detail, _user in recorder.records
    )


def test_skills_external_edit_triggers_background_index_rebuild(tmp_path):
    import time as _time

    class _FakeIndex:
        def __init__(self):
            self.rebuilds = 0

        def rebuild(self, namespace, items):
            self.rebuilds += 1
            return {"fts_indexed": len(items), "semantic_indexed": 0}

    index = _FakeIndex()
    manager, data = _make_skill_manager(tmp_path, embedding_index=index)
    baseline = index.rebuilds  # init reload() rebuilds inline

    _write_skill(data / "global", "indexed-skill")
    assert manager.refresh_if_stale(force=True) is True

    deadline = _time.monotonic() + 5.0
    while index.rebuilds <= baseline and _time.monotonic() < deadline:
        _time.sleep(0.01)
    assert index.rebuilds > baseline


# -- coarse-mtime fingerprints ------------------------------------------------
#
# File mtimes come from a coarse kernel clock (~1ms on Linux/ext4, ~15.6ms on
# Windows, 1-2s on older filesystems). Two writes inside one tick that keep the
# byte count leave (mtime, size) identical, so a fingerprint captured between
# them compares equal FOREVER and the second write is missed permanently.
#
# Every test below forces that collision with os.utime instead of racing the
# clock, so they pin the behavior deterministically rather than ~1-in-4 of the
# time (the natural flake rate measured for this pattern).


def test_fingerprint_detects_same_tick_same_size_rewrite(tmp_path):
    from nymeria.core.storage_paths import compare_fingerprint

    target = tmp_path / "store.json"
    target.write_text("A" * 64, encoding="utf-8")
    first, changed = compare_fingerprint(target, None)
    assert changed is True and first[2]  # racy: carries a content hash

    before = os.stat(target).st_mtime_ns
    target.write_text("B" * 64, encoding="utf-8")  # same size
    os.utime(target, ns=(before, before))  # same tick
    assert os.stat(target).st_mtime_ns == first[0]  # (mtime, size) unmoved

    _, changed = compare_fingerprint(target, first)
    assert changed is True


def test_fingerprint_settles_without_reporting_a_change(tmp_path):
    """The false-positive direction, which matters more than the miss.

    A fingerprint taken while a file was racy carries a hash; once the file is
    old enough to trust mtime again it must DROP that hash so it stops being
    re-read every sweep. If that downgrade were reported as a change it would
    re-embed the whole skill pool and write an EXTERNAL_EDIT audit line
    claiming a store was edited on disk when nothing touched it.
    """
    from nymeria.core.storage_paths import (
        RACY_FINGERPRINT_MARGIN_NS,
        compare_fingerprint,
    )

    target = tmp_path / "store.json"
    target.write_text("{}", encoding="utf-8")
    racy, _ = compare_fingerprint(target, None)
    assert racy[2]  # hashed while recent

    later = time.time_ns() + RACY_FINGERPRINT_MARGIN_NS * 2
    settled, changed = compare_fingerprint(target, racy, now_ns=later)
    assert changed is False  # no phantom edit
    assert settled[2] == ""  # converged: no longer re-hashed

    stable, changed = compare_fingerprint(target, settled, now_ns=later)
    assert changed is False and stable[2] == ""

    # A genuine later write is still caught off the hashless fingerprint,
    # because a quiet file's next write lands on a later tick by definition:
    # the hash was only dropped once mtime was margin-seconds old. Same SIZE
    # and a pinned later tick, so this proves the mtime path rather than
    # passing on a size difference or racing the real clock.
    target.write_text("[]", encoding="utf-8")
    bumped = stable[0] + 1_000_000
    os.utime(target, ns=(bumped, bumped))
    _, changed = compare_fingerprint(target, stable)
    assert changed is True


def test_unreadable_racy_file_never_records_the_trusted_quiet_hash(tmp_path):
    """``stat`` needs only directory search; ``open`` needs read on the file,
    so a racy file can be statted and not read. Recording "" there would
    assert that mtime is trustworthy and reintroduce the permanent same-tick
    miss; recording nothing would make a directory scan report the file
    REMOVED and evict a live definition over a transient error."""
    from nymeria.core import storage_paths
    from nymeria.core.storage_paths import (
        UNREADABLE_FINGERPRINT_HASH,
        compare_fingerprint,
    )

    target = tmp_path / "store.json"
    target.write_text("AAAA", encoding="utf-8")

    real_hash = storage_paths._content_hash
    storage_paths._content_hash = lambda path: None  # unreadable this once
    try:
        first, changed = compare_fingerprint(target, None)
    finally:
        storage_paths._content_hash = real_hash
    assert changed is True
    assert first[2] == UNREADABLE_FINGERPRINT_HASH  # not "", not dropped

    # Once readable again, the same-tick same-size rewrite is still caught.
    before = os.stat(target).st_mtime_ns
    target.write_text("BBBB", encoding="utf-8")
    os.utime(target, ns=(before, before))
    _, changed = compare_fingerprint(target, first)
    assert changed is True


def test_settle_declines_to_write_back_a_hash(tmp_path):
    """Settling is only ever a DOWNGRADE.

    A caller that snapshotted outside its lock may hold an older fingerprint
    than a concurrent scanner's. Equal (mtime, size) does not prove equal
    content here (that is the whole collision this module exists for), so
    writing back a stale HASH could hide an edit a peer already saw. Dropping
    the hash is safe in that race because it only asserts what mtime proves.
    """
    from nymeria.core.storage_paths import settle_fingerprint

    stored = (100, 8, "peer-saw-this-edit")
    assert settle_fingerprint(stored, (100, 8, "stale-snapshot")) is None
    assert settle_fingerprint(stored, (100, 8, "")) == (100, 8, "")
    # The (mtime, size) guard still applies to the downgrade itself.
    assert settle_fingerprint(stored, (101, 8, "")) is None
    assert settle_fingerprint(None, (100, 8, "")) is None


def test_atomic_write_never_widens_a_tightened_mode(tmp_path, monkeypatch):
    """The temp file must be born at the target's mode, not chmod'ed after.

    A temp created at the umask default and tightened afterwards is briefly
    group/world readable WITH the new bytes already in it, which would leak
    the contents of a 0600 file that a plain in-place write never widened.
    """
    _require_unprivileged_posix("file permission bits")
    from nymeria.core.storage_paths import write_text_atomic

    target = tmp_path / "secret.json"
    target.write_text("{}", encoding="utf-8")
    target.chmod(0o600)

    # Sample the temp's mode at the moment the content has landed but the
    # tightening chmod has not run yet. That instant is the whole window: a
    # temp created wide and narrowed afterwards is readable WITH the secret in
    # it, while a temp created narrow is never readable at all.
    seen = []
    real_chmod = os.chmod

    def _spy(path_arg, mode, *args, **kwargs):
        try:
            seen.append((stat.S_IMODE(os.stat(path_arg).st_mode),
                         os.stat(path_arg).st_size))
        except OSError:
            pass
        return real_chmod(path_arg, mode, *args, **kwargs)

    monkeypatch.setattr(os, "chmod", _spy)
    write_text_atomic(target, "secret-bytes")

    assert seen, "the mode carry-over path did not run"
    for mode, size in seen:
        assert size > 0, "sampled before the content landed; test is not probing the window"
        assert mode & 0o077 == 0, f"temp was {oct(mode)} with the secret already in it"
    assert stat.S_IMODE(target.stat().st_mode) == 0o600
    assert target.read_text(encoding="utf-8") == "secret-bytes"


def test_skills_same_tick_same_size_edit_hot_loads(tmp_path):
    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "demo-skill", body="Body v1")
    manager.reload()
    assert "Body v1" in manager.get("demo-skill").body

    skill_md = skill_dir / "SKILL.md"
    before = os.stat(skill_md).st_mtime_ns
    _write_skill(data / "global", "demo-skill", body="Body v2")  # same length
    os.utime(skill_md, ns=(before, before))

    assert "Body v2" in manager.get("demo-skill").body


def test_skills_same_tick_same_size_edit_is_audited(tmp_path, monkeypatch):
    """Seeing the edit and AUDITING it are separate contracts.

    The scan reports which keys changed and the audit consumes that verdict.
    Re-deriving the changed set at audit time would compare a settled
    (hashless) fingerprint against a hashed one and conclude "no change",
    dropping the audit line for exactly the same-tick edits this machinery
    exists to catch, while the hot-load above still passed.
    """
    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "demo-skill", body="Body v1")
    manager.reload()
    assert manager.get("demo-skill") is not None
    recorder.records.clear()  # the initial scan is not an external edit

    skill_md = skill_dir / "SKILL.md"
    before = os.stat(skill_md).st_mtime_ns
    _write_skill(data / "global", "demo-skill", body="Body v2")  # same length
    os.utime(skill_md, ns=(before, before))

    assert "Body v2" in manager.get("demo-skill").body
    assert [r[0] for r in recorder.records] == ["skills"]
    assert "demo-skill" in recorder.records[0][1]

    # Re-reading an unchanged file does not re-audit. (The settle-back-to-
    # hashless downgrade is a different branch, covered deterministically by
    # test_skills_settling_a_quiet_file_is_not_an_edit; the file here is
    # seconds old, so nothing has gone quiet yet.)
    recorder.records.clear()
    manager.get("demo-skill")
    assert recorder.records == []


def test_skills_settling_a_quiet_file_is_not_an_edit(tmp_path, monkeypatch):
    """The adopter-level settle path, forced rather than waited for.

    A cached fingerprint taken while the file was racy carries a hash. Once
    the file is old enough to trust mtime again, the sweep must DOWNGRADE the
    cached entry (so it stops re-hashing every sweep) without reporting an
    edit: a false positive here re-embeds the whole skill pool and writes an
    EXTERNAL_EDIT line claiming a store was edited when nothing touched it.
    Shrinking the trust margin is how the test reaches "quiet" without sleeping
    past it.
    """
    from nymeria.core import storage_paths

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    manager, data = _make_skill_manager(tmp_path)
    skill_dir = _write_skill(data / "global", "demo-skill", body="Body v1")
    manager.reload()
    key = str(skill_dir / "SKILL.md")
    assert manager._scan_sigs[key][2]  # hashed: written moments ago
    recorder.records.clear()

    monkeypatch.setattr(storage_paths, "RACY_FINGERPRINT_MARGIN_NS", 0)
    assert manager.refresh_if_stale(force=True) is False  # no phantom edit
    assert recorder.records == []
    assert manager._scan_sigs[key][2] == ""  # converged: no longer re-hashed
    assert "Body v1" in manager.get("demo-skill").body


def test_hooks_same_tick_same_size_edit_is_seen_and_audited(tmp_path, monkeypatch):
    """The highest-severity site: this cache has no other rescan path, so a
    missed edit keeps a stale hook (a standing prompt injection or a
    pre_tool_use guardrail) firing indefinitely."""
    from nymeria.core.hook_manager import HookManager

    recorder = _AuditRecorder()
    monkeypatch.setattr("nymeria.core.activity_log.log_external_edit", recorder)

    author = HookManager(tmp_path)
    reader = HookManager(tmp_path)
    author.add_hook("u1", name="original", event="done", text="hi")
    assert [h.name for h in reader.get_hooks_cached("u1")] == ["original"]

    # Raw edit that preserves the byte count and reuses the manager write's
    # tick: renaming to another 8-character name.
    path = reader._path_for("u1")
    before = os.stat(path).st_mtime_ns
    raw = path.read_text(encoding="utf-8")
    assert '"original"' in raw
    path.write_text(raw.replace('"original"', '"repl@ced"'), encoding="utf-8")
    os.utime(path, ns=(before, before))
    assert os.stat(path).st_mtime_ns == before

    assert [h.name for h in reader.get_hooks_cached("u1")] == ["repl@ced"]
    assert ("hooks", "hook store file edited on disk", "u1") in recorder.records


def test_teams_same_tick_same_size_edit_is_seen(tmp_path):
    from nymeria.core.team_manager import TeamManager

    author = TeamManager(tmp_path)
    reader = TeamManager(tmp_path)
    team = author.create_team("u1", name="Alpha")
    assert [t.name for t in reader.get_store_cached("u1").teams] == ["Alpha"]

    path = reader._path_for("u1")
    before = os.stat(path).st_mtime_ns
    raw = path.read_text(encoding="utf-8")
    path.write_text(raw.replace('"Alpha"', '"Omega"'), encoding="utf-8")
    os.utime(path, ns=(before, before))

    assert [t.name for t in reader.get_store_cached("u1").teams] == ["Omega"]
    assert team.id  # sanity: the store really was populated through the API


def test_custom_tools_same_tick_same_size_edit_hot_loads(tmp_path):
    loader = _make_loader(tmp_path)
    path = tmp_path / "ext_demo.json"
    path.write_text(_tool_json("ext_demo", description="aaaa"), encoding="utf-8")
    assert loader.get_definition("ext_demo").description == "aaaa"

    before = os.stat(path).st_mtime_ns
    path.write_text(_tool_json("ext_demo", description="bbbb"), encoding="utf-8")
    os.utime(path, ns=(before, before))

    assert loader.get_definition("ext_demo").description == "bbbb"


def test_mcp_registry_same_tick_same_size_edit_hot_loads(tmp_path):
    from nymeria.core.mcp_servers import MCPServerRegistry

    registry = MCPServerRegistry(servers_dir=tmp_path)
    registry.EXTERNAL_REFRESH_INTERVAL_SECONDS = 0.0
    server_json = json.dumps(
        {"id": "srv", "name": "Srv", "transport": "http", "url": "https://aaa.example.com"}
    )
    path = tmp_path / "srv.json"
    path.write_text(server_json, encoding="utf-8")
    registry.refresh_if_stale(force=True)
    assert registry.get_server("srv").url == "https://aaa.example.com"

    before = os.stat(path).st_mtime_ns
    path.write_text(
        server_json.replace("https://aaa.example.com", "https://bbb.example.com"),
        encoding="utf-8",
    )
    os.utime(path, ns=(before, before))
    registry.refresh_if_stale(force=True)

    assert registry.get_server("srv").url == "https://bbb.example.com"
