"""Shell completion script generators for bash, zsh, and fish."""

from __future__ import annotations

import argparse
from typing import Sequence


def _collect_subcommands(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """Extract subcommand name → sub-parser mapping."""
    result: dict[str, argparse.ArgumentParser] = {}
    if parser._subparsers is None:
        return result
    for action in parser._subparsers._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, subparser in action.choices.items():
                result[name] = subparser
    return result


def _collect_flags(parser: argparse.ArgumentParser) -> list[str]:
    """Extract all option strings (--foo, -f) from a parser."""
    flags: list[str] = []
    for action in parser._actions:
        if action.option_strings:
            flags.extend(action.option_strings)
    return flags


def _collect_flag_values(parser: argparse.ArgumentParser) -> dict[str, list[str]]:
    """Map long flags to their known choices, if any."""
    result: dict[str, list[str]] = {}
    for action in parser._actions:
        if action.choices and action.option_strings:
            choices = [str(c) for c in action.choices]
            for opt in action.option_strings:
                if opt.startswith("--"):
                    result[opt] = choices
    return result


def generate_bash(parser: argparse.ArgumentParser) -> str:
    subcommands = _collect_subcommands(parser)
    top_flags = _collect_flags(parser)

    subcmd_names = sorted(subcommands.keys())
    top_words = subcmd_names + [f for f in top_flags if f.startswith("--")]

    lines = [
        "# Bash completion for Nymeria (python run.py)",
        "# Generated by: python run.py completion bash",
        "#",
        "# Installation:",
        "#   python run.py completion bash > /etc/bash_completion.d/nymeria",
        "# Or for the current user:",
        "#   python run.py completion bash >> ~/.bashrc",
        "#   source ~/.bashrc",
        "",
        "_nymeria_completions() {",
        '    local cur prev subcmd',
        '    COMPREPLY=()',
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        "",
        "    # Find the subcommand",
        "    subcmd=''",
        "    for word in \"${COMP_WORDS[@]}\"; do",
        "        case \"$word\" in",
        f"            {' | '.join(subcmd_names)})",
        "                subcmd=\"$word\"",
        "                break",
        "                ;;",
        "        esac",
        "    done",
        "",
        "    # Top-level: complete subcommands and global flags",
        '    if [[ -z "$subcmd" ]]; then',
        f"        COMPREPLY=( $(compgen -W '{' '.join(top_words)}' -- \"$cur\") )",
        "        return 0",
        "    fi",
        "",
        "    # Per-subcommand completions",
        '    case "$subcmd" in',
    ]

    for name, subparser in sorted(subcommands.items()):
        flags = _collect_flags(subparser)
        flag_values = _collect_flag_values(subparser)
        long_flags = [f for f in flags if f.startswith("--")]

        lines.append(f"        {name})")

        # Add choice-based completions for flags with known values
        for flag, choices in sorted(flag_values.items()):
            lines.append(f'            if [[ "$prev" == "{flag}" ]]; then')
            lines.append(f"                COMPREPLY=( $(compgen -W '{' '.join(choices)}' -- \"$cur\") )")
            lines.append("                return 0")
            lines.append("            fi")

        lines.append(f"            COMPREPLY=( $(compgen -W '{' '.join(long_flags)}' -- \"$cur\") )")
        lines.append("            ;;")

    lines.extend([
        "    esac",
        "    return 0",
        "}",
        "",
        'complete -F _nymeria_completions -o default "run.py"',
        'complete -F _nymeria_completions -o default "nymeria"',
        "",
    ])

    return "\n".join(lines)


def generate_zsh(parser: argparse.ArgumentParser) -> str:
    subcommands = _collect_subcommands(parser)

    lines = [
        "#compdef nymeria run.py",
        "# Zsh completion for Nymeria (python run.py)",
        "# Generated by: python run.py completion zsh",
        "#",
        "# Installation:",
        "#   python run.py completion zsh > ~/.zsh/completions/_nymeria",
        "#   # Ensure ~/.zsh/completions is in your fpath:",
        "#   #   fpath=(~/.zsh/completions $fpath)",
        "#   # Then reload completions:",
        "#   #   autoload -Uz compinit && compinit",
        "",
        "_nymeria() {",
        "    local -a subcommands",
        "    subcommands=(",
    ]

    for name, subparser in sorted(subcommands.items()):
        desc = (subparser.description or "").split("\n")[0].strip()
        if not desc:
            if parser._subparsers is not None:
                for action in parser._subparsers._actions:
                    if isinstance(action, argparse._SubParsersAction):
                        help_text = action.choices.get(name)
                        if help_text and hasattr(help_text, "description"):
                            desc = (help_text.description or "").split("\n")[0].strip()
            if not desc:
                desc = name
        desc = desc.replace("'", "'\\''")
        lines.append(f"        '{name}:{desc}'")

    lines.extend([
        "    )",
        "",
        "    _arguments -C \\",
        "        '1:subcommand:->subcmd' \\",
        "        '*::arg:->args'",
        "",
        "    case $state in",
        "        subcmd)",
        "            _describe 'subcommand' subcommands",
        "            ;;",
        "        args)",
        "            case $words[1] in",
    ])

    for name, subparser in sorted(subcommands.items()):
        flags = _collect_flags(subparser)
        flag_values = _collect_flag_values(subparser)
        long_flags = sorted(set(f for f in flags if f.startswith("--")))

        lines.append(f"                {name})")
        lines.append("                    _arguments \\")

        flag_lines: list[str] = []
        for flag in long_flags:
            choices = flag_values.get(flag)
            if choices:
                choices_str = " ".join(choices)
                flag_lines.append(f"                        '{flag}[]:choice:({choices_str})'")
            else:
                flag_lines.append(f"                        '{flag}[]'")

        lines.append(" \\\n".join(flag_lines) if flag_lines else "                        '*:'")
        lines.append("                    ;;")

    lines.extend([
        "            esac",
        "            ;;",
        "    esac",
        "}",
        "",
        "_nymeria",
        "",
    ])

    return "\n".join(lines)


def generate_fish(parser: argparse.ArgumentParser) -> str:
    subcommands = _collect_subcommands(parser)

    lines = [
        "# Fish completion for Nymeria (python run.py)",
        "# Generated by: python run.py completion fish",
        "#",
        "# Installation:",
        "#   python run.py completion fish > ~/.config/fish/completions/nymeria.fish",
        "",
        "# Disable file completions by default",
        "complete -c nymeria -f",
        "complete -c run.py -f",
        "",
        "# Helper: check if a subcommand has been given",
        "function __nymeria_no_subcommand",
        "    set -l cmd (commandline -opc)",
        "    for word in $cmd[2..]",
        "        switch $word",
    ]

    subcmd_names = sorted(subcommands.keys())
    for name in subcmd_names:
        lines.append(f"            case {name}")
        lines.append("                return 1")

    lines.extend([
        "        end",
        "    end",
        "    return 0",
        "end",
        "",
        "# Subcommands",
    ])

    for name, subparser in sorted(subcommands.items()):
        desc = name
        if parser._subparsers is not None:
            for action in parser._subparsers._actions:
                if isinstance(action, argparse._SubParsersAction):
                    sp = action.choices.get(name)
                    if sp:
                        raw = getattr(sp, "description", "") or ""
                        first = raw.split("\n")[0].strip()
                        if first:
                            desc = first
        desc = desc.replace("'", "\\'")
        lines.append(
            f"complete -c nymeria -c run.py -n __nymeria_no_subcommand "
            f"-a {name} -d '{desc}'"
        )

    lines.append("")
    lines.append("# Per-subcommand flags")

    for name, subparser in sorted(subcommands.items()):
        flag_values = _collect_flag_values(subparser)

        for action in subparser._actions:
            if not action.option_strings:
                continue
            long = [o for o in action.option_strings if o.startswith("--")]
            short = [o for o in action.option_strings if o.startswith("-") and not o.startswith("--")]

            desc = (action.help or "").replace("'", "\\'")

            parts = ["complete -c nymeria -c run.py"]
            parts.append(f"-n '__fish_seen_subcommand_from {name}'")
            if long:
                parts.append(f"-l {long[0].lstrip('-')}")
            if short:
                parts.append(f"-s {short[0].lstrip('-')}")
            if desc:
                parts.append(f"-d '{desc}'")

            choices = flag_values.get(long[0]) if long else None
            if choices:
                parts.append(f"-ra '{' '.join(choices)}'")

            lines.append(" ".join(parts))

    lines.append("")

    return "\n".join(lines)


_GENERATORS = {
    "bash": generate_bash,
    "zsh": generate_zsh,
    "fish": generate_fish,
}

SUPPORTED_SHELLS: Sequence[str] = tuple(_GENERATORS.keys())


def generate(shell: str, parser: argparse.ArgumentParser) -> str:
    generator = _GENERATORS.get(shell)
    if generator is None:
        raise ValueError(
            f"Unsupported shell: {shell!r}. "
            f"Supported: {', '.join(SUPPORTED_SHELLS)}"
        )
    return generator(parser)
